import { AlertTriangle, CheckCircle, ShieldAlert, Sparkles } from "lucide-react";
import type { InspectionResponse } from "../../types/inspection";

interface PredictionCardProps {
  inspection: InspectionResponse;
}

export const PredictionCard: React.FC<PredictionCardProps> = ({ inspection }) => {
  const { predicted_condition, confidence, health_assessment, model_metadata } = inspection;

  const getRiskBadge = (risk: string) => {
    switch (risk.toUpperCase()) {
      case "LOW":
        return {
          bg: "bg-emerald-500/10 text-emerald-400 border-emerald-500/30",
          icon: <CheckCircle className="w-4 h-4 text-emerald-400" />
        };
      case "MEDIUM":
        return {
          bg: "bg-amber-500/10 text-amber-400 border-amber-500/30",
          icon: <AlertTriangle className="w-4 h-4 text-amber-400" />
        };
      case "HIGH":
      case "CRITICAL":
        return {
          bg: "bg-rose-500/10 text-rose-400 border-rose-500/30",
          icon: <ShieldAlert className="w-4 h-4 text-rose-400" />
        };
      default:
        return {
          bg: "bg-slate-500/10 text-slate-400 border-slate-500/30",
          icon: <AlertTriangle className="w-4 h-4 text-slate-400" />
        };
    }
  };

  const riskInfo = getRiskBadge(health_assessment.risk_level);
  const healthPercent = health_assessment.health_score;

  return (
    <div className="bg-[#0B101D] border border-slate-800/90 rounded-2xl p-6 shadow-2xl shadow-black/60 relative overflow-hidden">
      {/* Demo Banner */}
      {model_metadata.is_demo_preview && (
        <div className="bg-amber-500/15 border-b border-amber-500/30 -mt-6 -mx-6 mb-5 px-4 py-2.5 flex items-center justify-between">
          <span className="text-xs font-bold uppercase tracking-wider text-amber-300 flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5" />
            Demo Visualization Mode
          </span>
          <span className="text-[11px] text-amber-200/80">
            Illustrative preview — Not generated by model
          </span>
        </div>
      )}

      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-5 border-b border-slate-800/80">
        <div>
          <span className="text-xs font-bold uppercase tracking-wider text-amber-400/90">
            Detected Condition
          </span>
          <h3 className="text-2xl font-black text-white tracking-tight mt-1 flex items-center gap-2">
            {predicted_condition}
          </h3>
        </div>

        {/* Risk Level Badge */}
        <div className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-xs font-semibold ${riskInfo.bg}`}>
          {riskInfo.icon}
          <span>{health_assessment.risk_level} RISK</span>
        </div>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-5">
        {/* Confidence Score */}
        <div className="bg-slate-900/90 rounded-xl p-4 border border-slate-800/80">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-1.5">
              <span className="text-xs font-medium text-slate-400">Model Confidence</span>
              {inspection.confidence_level && (
                <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded border uppercase ${
                  inspection.confidence_level === "HIGH"
                    ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/30"
                    : inspection.confidence_level === "MODERATE"
                    ? "bg-amber-500/10 text-amber-400 border-amber-500/30"
                    : "bg-rose-500/10 text-rose-400 border-rose-500/30"
                }`}>
                  {inspection.confidence_level}
                </span>
              )}
            </div>
            <span className="text-sm font-mono font-bold text-amber-400">
              {(confidence * 100).toFixed(1)}%
            </span>
          </div>
          <div className="w-full bg-slate-800 rounded-full h-2 overflow-hidden">
            <div
              className={`h-2 rounded-full transition-all duration-500 ${
                confidence >= 0.85
                  ? "bg-emerald-500"
                  : confidence >= 0.60
                  ? "bg-amber-500"
                  : "bg-rose-500"
              }`}
              style={{ width: `${Math.min(100, confidence * 100)}%` }}
            />
          </div>
          <p className="text-[11px] text-slate-500 mt-2">
            Softmax output probability for top classified class
          </p>
        </div>

        {/* Health Score */}
        <div className="bg-slate-900/90 rounded-lg p-4 border border-slate-800/80">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-medium text-slate-400">Panel Health Index</span>
            <span className={`text-sm font-mono font-bold ${
              healthPercent > 70 ? "text-emerald-400" : healthPercent > 40 ? "text-amber-400" : "text-rose-400"
            }`}>
              {health_assessment.health_score} / 100
            </span>
          </div>
          <div className="w-full bg-slate-800 rounded-full h-2 overflow-hidden">
            <div
              className={`h-2 rounded-full transition-all duration-500 ${
                healthPercent > 70
                  ? "bg-emerald-500"
                  : healthPercent > 40
                  ? "bg-amber-500"
                  : "bg-rose-500"
              }`}
              style={{ width: `${healthPercent}%` }}
            />
          </div>
          <p className="text-[11px] text-slate-500 mt-2">
            Rule-based assessment derived from detected state
          </p>
        </div>
      </div>

      {/* Low Confidence Advisory Alert */}
      {confidence < 0.60 && (
        <div className="mt-4 p-3 bg-amber-500/10 border border-amber-500/30 rounded-lg flex items-start gap-2.5 text-xs text-amber-300">
          <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5 text-amber-400" />
          <div>
            <span className="font-semibold text-amber-200">Advisory: Low Confidence Classification (&lt; 60%). </span>
            Predictions with low probability should be verified with manual physical or thermographic inspection before taking field action.
          </div>
        </div>
      )}
    </div>
  );
};
