"""
SolarSentinel AI - Demo Mode & Capability Reporting API
"""

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile, status

from backend.app.dependencies import get_model_service
from backend.app.schemas.health import DemoStatusResponse
from backend.app.schemas.inspection import InspectionResponse
from backend.app.services.inspection_service import ImageValidationError, InspectionService
from backend.app.services.model_service import ModelService

router = APIRouter(prefix="/demo", tags=["Demo Visualization"])


@router.get(
    "/status",
    response_model=DemoStatusResponse,
    summary="Get Current Application Operation Mode",
    description="Reports whether backend is operating in REAL_MODEL mode or DEMO_ONLY mode."
)
async def get_demo_status(ms: ModelService = Depends(get_model_service)) -> DemoStatusResponse:
    if ms.is_loaded:
        return DemoStatusResponse(
            mode="REAL_MODEL",
            model_available=True,
            message="Active neural network weights are loaded. Full production inference and Grad-CAM are operational."
        )
    else:
        return DemoStatusResponse(
            mode="DEMO_ONLY",
            model_available=False,
            message=(
                "Trained weights are not currently present on disk. "
                "The application is operating in DEMO_ONLY mode. "
                "No synthetic predictions will be returned by the standard /inspect endpoint."
            ),
            setup_instructions=[
                "1. Place raw solar panel images into `data/raw/` organized by class directory.",
                "2. Validate dataset: `python ml/training/validate_dataset.py --data_dir data/raw`",
                "3. Train model: `python ml/training/train.py --data_dir data/raw`",
                "4. Restart the backend to automatically load `ml/models/solar_sentinel_vgg16.keras`."
            ]
        )


@router.post(
    "/inspect",
    response_model=InspectionResponse,
    summary="Generate Illustrative Demo Visualization (Clearly Labeled)",
    description=(
        "Generates an illustrative UI preview of an inspection report. "
        "Strictly labeled: 'DEMO VISUALIZATION: Results are NOT generated by the trained neural network.' "
        "Allows full UI testing without fabricating model metrics."
    )
)
async def inspect_demo_preview(
    file: UploadFile = File(..., description="Sample solar panel image")
) -> InspectionResponse:
    try:
        file_bytes = await file.read()
        return InspectionService.process_demo_preview(
            file_bytes=file_bytes,
            filename=file.filename or "demo_sample.jpg"
        )
    except ImageValidationError as e:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(e)
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Demo preview error: {str(e)}"
        )


@router.get(
    "/sample-images",
    summary="Get List of Available Sample Images for Testing",
    description="Returns metadata for 6 sample solar panel images covering each verified condition."
)
async def get_sample_images():
    """Returns accessible sample images representing each of the 6 classes for interactive testing."""
    samples = [
        {
            "id": "sample-clean",
            "class_name": "Clean",
            "filename": "Clean (1).jpeg",
            "relative_path": "dataset/Faulty_solar_panel/Clean/Clean (1).jpeg",
            "description": "Nominal, clear photovoltaic cell surface with no obstruction."
        },
        {
            "id": "sample-dusty",
            "class_name": "Dusty",
            "filename": "Dust (1).jpg",
            "relative_path": "dataset/Faulty_solar_panel/Dusty/Dust (1).jpg",
            "description": "Accumulated particulate layer causing diffuse solar attenuation."
        },
        {
            "id": "sample-bird-drop",
            "class_name": "Bird-drop",
            "filename": "Bird (1).jpeg",
            "relative_path": "dataset/Faulty_solar_panel/Bird-drop/Bird (1).jpeg",
            "description": "Localized opaque organic deposit posing hotspot cell heating risks."
        },
        {
            "id": "sample-snow-covered",
            "class_name": "Snow-Covered",
            "filename": "Snow (1).jpg",
            "relative_path": "dataset/Faulty_solar_panel/Snow-Covered/Snow (1).jpg",
            "description": "Partial or complete surface occlusion by winter snow coverage."
        },
        {
            "id": "sample-electrical-damage",
            "class_name": "Electrical-damage",
            "filename": "Electrical (1).jpg",
            "relative_path": "dataset/Faulty_solar_panel/Electrical-damage/Electrical (1).jpg",
            "description": "Thermal hotspot discoloration or cell degradation requiring technician review."
        },
        {
            "id": "sample-physical-damage",
            "class_name": "Physical-Damage",
            "filename": "Physical (1).jpg",
            "relative_path": "dataset/Faulty_solar_panel/Physical-Damage/Physical (1).jpg",
            "description": "Surface glass fractures or micro-crack patterns requiring module inspection."
        }
    ]
    return {
        "count": len(samples),
        "samples": samples
    }


@router.get(
    "/sample-images/{sample_id}",
    summary="Download or Preview a Sample Image by ID",
    description="Returns the binary image content for the requested sample ID."
)
async def get_sample_image_file(sample_id: str):
    """Streams the requested sample image."""
    from fastapi.responses import FileResponse
    import os

    samples_map = {
        "sample-clean": "dataset/Faulty_solar_panel/Clean/Clean (1).jpeg",
        "sample-dusty": "dataset/Faulty_solar_panel/Dusty/Dust (1).jpg",
        "sample-bird-drop": "dataset/Faulty_solar_panel/Bird-drop/Bird (1).jpeg",
        "sample-snow-covered": "dataset/Faulty_solar_panel/Snow-Covered/Snow (1).jpg",
        "sample-electrical-damage": "dataset/Faulty_solar_panel/Electrical-damage/Electrical (1).jpg",
        "sample-physical-damage": "dataset/Faulty_solar_panel/Physical-Damage/Physical (1).jpg",
    }

    if sample_id not in samples_map:
        raise HTTPException(status_code=404, detail=f"Sample image '{sample_id}' not found.")

    rel_path = samples_map[sample_id]
    if not os.path.exists(rel_path):
        raise HTTPException(status_code=404, detail=f"Sample file '{rel_path}' does not exist on disk.")

    media_type = "image/jpeg" if rel_path.lower().endswith((".jpg", ".jpeg")) else "image/png"
    return FileResponse(rel_path, media_type=media_type)


