"""
SolarSentinel AI - Model Service (Singleton)
Loads Keras VGG16 model and Grad-CAM Explainer once at application startup.
Provides thread-safe forward pass and explanation methods.
"""

import json
import os
from typing import Dict, List, Optional, Tuple, Union
import numpy as np
from PIL import Image

from backend.app.core.config import settings
from backend.app.core.logging import logger
from ml.explainability.gradcam import GradCAMExplainer, GradCAMResult
from ml.inference.predict import ModelNotLoadedError
from ml.inference.preprocessing import preprocess_image


class ModelService:
    """Singleton service managing deep learning inference and Grad-CAM explainability."""

    _instance: Optional["ModelService"] = None

    def __init__(self):
        self.model = None
        self.model_head_a = None
        self.explainer: Optional[GradCAMExplainer] = None
        self.class_names: List[str] = self._load_class_names()
        self.input_size: Tuple[int, int] = (
            settings.MODEL_INPUT_HEIGHT,
            settings.MODEL_INPUT_WIDTH
        )
        self.is_loaded: bool = False

    @classmethod
    def get_instance(cls) -> "ModelService":
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def _load_class_names(self) -> List[str]:
        """Loads canonical verified class names from metadata directory."""
        if os.path.exists(settings.CLASS_NAMES_PATH):
            try:
                with open(settings.CLASS_NAMES_PATH, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    return data.get("classes", [])
            except Exception as e:
                logger.warning(f"Could not read class names from {settings.CLASS_NAMES_PATH}: {e}")

        # Default fallback to verified classes from Phase 1 audit
        return [
            "Bird-drop",
            "Clean",
            "Dusty",
            "Electrical-damage",
            "Physical-Damage",
            "Snow-Covered"
        ]

    def load_model(self) -> bool:
        """
        Loads the trained models once during application startup lifespan.
        Returns True if primary model was loaded, False if weights do not exist.
        """
        if not os.path.exists(settings.MODEL_PATH):
            logger.warning(
                f"Model weights file not found at: {settings.MODEL_PATH}. "
                f"Application will operate in MODEL_UNAVAILABLE mode. "
                f"Trained weights can be generated by running `python ml/training/train.py`."
            )
            self.model = None
            self.model_head_a = None
            self.explainer = None
            self.is_loaded = False
            return False

        try:
            import tensorflow as tf
            self.model = tf.keras.models.load_model(settings.MODEL_PATH)

            # Dynamically detect model expected input resolution
            in_shape = self.model.input_shape
            if isinstance(in_shape, list):
                in_shape = in_shape[0]
            if in_shape and len(in_shape) > 2 and in_shape[1] is not None and in_shape[2] is not None:
                self.input_size = (int(in_shape[1]), int(in_shape[2]))
                logger.info(f"Dynamically detected model input resolution: {self.input_size}")
            if settings.USE_ENSEMBLE and os.path.exists(settings.MODEL_HEAD_A_PATH):
                try:
                    logger.info(f"Loading secondary Head A model for ensemble from {settings.MODEL_HEAD_A_PATH}...")
                    self.model_head_a = tf.keras.models.load_model(settings.MODEL_HEAD_A_PATH)
                    logger.info("Ensemble mode active: Dual-VGG16 (Exp 1 + Exp 2) initialized.")
                except Exception as e:
                    logger.warning(f"Could not load secondary ensemble model: {e}")
                    self.model_head_a = None
            else:
                self.model_head_a = None

            logger.info("Initializing Grad-CAM Explainer on primary model backbone...")
            self.explainer = GradCAMExplainer(
                model=self.model,
                class_names=self.class_names,
                input_size=self.input_size
            )
            self.is_loaded = True
            logger.info(f"SolarSentinel Model Service successfully initialized ({len(self.class_names)} classes).")
            return True
        except Exception as e:
            logger.error(f"Failed to load model from {settings.MODEL_PATH}: {e}", exc_info=True)
            self.model = None
            self.model_head_a = None
            self.explainer = None
            self.is_loaded = False
            return False

    def predict(self, image: Image.Image) -> Dict:
        """Executes forward pass and returns verified probabilities (blended if ensemble is active)."""
        if not self.is_loaded or self.model is None:
            raise ModelNotLoadedError(
                "Model weights are not currently loaded. "
                "Per scientific honesty guidelines, inference requests are disabled until trained weights are available."
            )

        # Preprocess using canonical inference pipeline
        tensor = preprocess_image(image, target_size=self.input_size, expand_batch=True)

        # Primary model forward pass (Exp 2 Head B)
        raw_output_b = self.model.predict(tensor, verbose=0)[0]

        # If ensemble is active, apply calibrated temperature-scaled posterior blend (T1=0.7, T2=0.85, w=0.5)
        if self.model_head_a is not None:
            raw_output_a = self.model_head_a.predict(tensor, verbose=0)[0]
            
            # Temperature-calibrated softmax
            log_a = np.log(np.clip(raw_output_a, 1e-7, 1.0)) / 0.7
            exp_a = np.exp(log_a - np.max(log_a))
            p_a = exp_a / np.sum(exp_a)

            log_b = np.log(np.clip(raw_output_b, 1e-7, 1.0)) / 0.85
            exp_b = np.exp(log_b - np.max(log_b))
            p_b = exp_b / np.sum(exp_b)

            probs = 0.5 * p_a + 0.5 * p_b
        else:
            probs = raw_output_b

        # Softmax guarantee
        if not np.isclose(np.sum(probs), 1.0, atol=1e-2):
            exp_p = np.exp(probs - np.max(probs))
            probs = exp_p / np.sum(exp_p)

        pred_idx = int(np.argmax(probs))
        confidence = float(probs[pred_idx])

        class_probabilities = {
            cls_name: round(float(probs[i]), 4)
            for i, cls_name in enumerate(self.class_names)
            if i < len(probs)
        }

        predicted_condition = (
            self.class_names[pred_idx]
            if pred_idx < len(self.class_names)
            else f"Class_{pred_idx}"
        )

        return {
            "predicted_condition": predicted_condition,
            "confidence": round(confidence, 4),
            "class_index": pred_idx,
            "class_probabilities": class_probabilities
        }

    def explain(self, image: Image.Image, target_class_index: Optional[int] = None) -> GradCAMResult:
        """Generates Grad-CAM visual explanation."""
        if not self.is_loaded or self.explainer is None:
            raise ModelNotLoadedError("Grad-CAM explainer is not available without loaded model weights.")

        return self.explainer.explain(
            image_source=image,
            target_class_index=target_class_index,
            overlay_alpha=0.5
        )


model_service = ModelService.get_instance()
