"""
SolarSentinel AI - Inspection Pydantic Schemas
Defines request and response contracts for solar panel condition inspections.
Strictly adheres to MODEL_CONTRACT.md and GRADCAM_CONTRACT.md.
"""

from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class GradCAMImages(BaseModel):
    """Base64 data URIs for rendered inspection visualizations."""
    original: str = Field(..., description="Original image as base64 PNG data URI")
    heatmap: str = Field(..., description="Colorized Grad-CAM heatmap as base64 PNG data URI")
    overlay: str = Field(..., description="Heatmap blended with original image as base64 PNG data URI")


class ExplainabilityPayload(BaseModel):
    """Grad-CAM attribution data and scientific disclaimer."""
    target_class_index: int = Field(..., description="Class index visualized by Grad-CAM")
    target_class_name: str = Field(..., description="Class name visualized by Grad-CAM")
    target_layer_name: str = Field(..., description="Convolutional layer extracted for attribution")
    original_dimensions: List[int] = Field(..., description="[height, width] of input image")
    disclaimer: str = Field(
        "Grad-CAM visualizes image regions that contributed strongly to the model's classification. "
        "It reflects neural network feature activations and does not constitute precise physical "
        "defect boundary detection or certified diagnostic certainty.",
        description="Mandatory scientific language disclaimer"
    )
    images: GradCAMImages = Field(..., description="Rendered image set")


class HealthAssessment(BaseModel):
    """Rule-based maintenance assessment derived from predicted condition."""
    health_score: int = Field(..., ge=0, le=100, description="Rule-based score from 0 (critical) to 100 (optimal)")
    risk_level: str = Field(..., description="LOW, MEDIUM, HIGH, or CRITICAL")
    maintenance_priority: str = Field(..., description="NONE, ROUTINE, ELEVATED, SCHEDULED, URGENT, or IMMEDIATE")
    recommendation: str = Field(..., description="Actionable maintenance guidance")
    methodology_note: str = Field(
        "The condition prediction is generated by an image classification model. "
        "The health score and maintenance guidance are rule-based assessments derived from the predicted condition.",
        description="Scientific separation notice"
    )


class ModelMetadata(BaseModel):
    """Execution metadata and runtime details."""
    architecture: str = Field("VGG16 Transfer Learning (Keras 3)", description="Underlying CNN backbone")
    input_dimensions: List[int] = Field([244, 244, 3], description="Network input resolution")
    is_demo_preview: bool = Field(False, description="Flag indicating if payload is an illustrative demo preview")


class InspectionResponse(BaseModel):
    """Complete structured inspection payload returned to clients."""
    inspection_id: str = Field(..., description="Unique UUID for this inspection session")
    timestamp: str = Field(..., description="UTC ISO timestamp of inspection execution")
    filename: str = Field(..., description="Name of uploaded image file")
    predicted_condition: str = Field(..., description="Top classified solar panel condition")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model softmax probability for top condition")
    confidence_level: str = Field(
        "HIGH",
        description="Transparent UI interpretation: HIGH (>=0.85), MODERATE (0.60-0.85), or LOW (<0.60)"
    )
    class_probabilities: Dict[str, float] = Field(..., description="Probability distribution across all verified classes")
    all_classes: List[str] = Field(..., description="List of all class names in model vocabulary")
    health_assessment: HealthAssessment = Field(..., description="Rule-based solar panel condition assessment")
    explainability: ExplainabilityPayload = Field(..., description="Grad-CAM visual explanation")
    model_metadata: ModelMetadata = Field(..., description="Model and runtime metadata")



class ErrorResponse(BaseModel):
    """Structured error message schema."""
    error_code: str = Field(..., description="Machine-readable error category")
    detail: str = Field(..., description="User-facing explanatory message")
    timestamp: str = Field(..., description="UTC ISO timestamp")
